### ISSUE TITLE
Loops

### ISSUE THREAD

**Issue by gee666** [chrisgoringe/Comfy-Custom-Node-How-To#11]
I need a simple loop logic, is there any idea how to implement it?
I imagine having one node "LoopStart" and one node "LoopEnd", which will decide, if it should activate a connection back to start or forward to the next nodes, depending of the loop index. Though I can't find any information if it's possible at all to decide to activate or not activate certain outputs/connections and also I guess ComfyUI might block the workflow with loops. 

Would you give any advice?

**Comment by chrisgoringe** [comment]
I'd advise you not to do this :).

The way Comfy works is to submit a complete prompt at the start - modifying the logic afterwards is not at all easy...
