### ISSUE TITLE
Propose documentation addition for INPUT_TYPES

### ISSUE THREAD

**Issue by corbin-hayden13** [chrisgoringe/Comfy-Custom-Node-How-To#23]
I propose an addition to custom widgets documentation regarding passing serialized custom widget data from javascript to python. Credit goes to rgthree for finding an awesome solution:

This `ContainsAnyDict` class creates an easy way to receive serialized data from custom widgets from javascript as kwargs to the `FUNCTION` in python whereas even if the custom widgets were serialized they would not be passed to the function in any capacity.
 
```python
class ContainsAnyDict(dict):
    def __contains__(self, key):
        return True
...

@classmethod
def INPUT_TYPES(s):
    return {
        "required": {},
        "optional": ContainsAnyDict()
    }
```

**Comment by chrisgoringe** [comment]
Thanks. I'm not making changes here any more, instead I'm working on the documentation at [docs.comfy.org](https://docs.comfy.org/). I'll be adding this over there!
