### ISSUE TITLE
Why does the "object of type 'int' has no len()" error occur here?

### ISSUE THREAD

**Issue by tusharbhutt** [chrisgoringe/Comfy-Custom-Node-How-To#6]
Hi,

ChatGPT (please don't laugh, I'm not a programmer) tells me this code should convert a FLOAT to an INT, but every time I run it, I get an error of: 

object of type 'int' has no len()

```
  File "C:\Applications\StableDiffusion\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\Applications\StableDiffusion\ComfyUI\execution.py", line 96, in get_output_data
    output_is_list = [False] * len(results[0])
```

This is the code below.  Appreciate any help provided, and if this is the wrong place to ask for help, please close :)
    
    
```
    class EndlessNode_FloattoInt:
	CATEGORY = "Endless 🌌/Converters"

	def __init__(self):
		pass	
		
	@classmethod
	def INPUT_TYPES(cls):
		return {
			"required": {"FloatValue": ("FLOAT", {"default": 0.0})},
		}

	RETURN_TYPES = ("INT",) 
	FUNCTION = "inputfloat"

	def inputfloat(self, FloatValue):
		return int(FloatValue)

```

**Comment by chrisgoringe** [comment]
Because you always need to return a tuple, not just a a value, even if you only have one return (even if zero!)

So 

return int(FloatValue)

Needs to be 

return (int(FloatValue),)

Don't forget the comma!!

**Comment by chrisgoringe** [comment]
The error comes from the execution code getting the return (an int), expecting a tuple, and trying to measure its length

**Comment by tusharbhutt** [comment]
Thanks so much, could've sworn I had tried that as well... 

OH!  I had, but that was when the input line said

` "required": {"FloatValue": ("FLOAT", {"default": 0.0,},)},`
 
 I guess I got comma happy there... with the **},)},**
 
 Thanks for your help!

**Comment by chrisgoringe** [comment]
Can never have too many commas in python :)
