### ISSUE TITLE
Not an Issue, but a thank you :)

### ISSUE THREAD

**Issue by aegis72** [chrisgoringe/Comfy-Custom-Node-How-To#7]
I'm amazed on how few resources there are on this topic. I'm trying to make some very simple utility nodes that load images and/or embed videos for contextual  training inside of comfy, and haven't been able to find anything until now.

**Comment by aegis72** [comment]
Is there a good reference that tells one what sort of things can be placed into a node? IE, is there a way to place HTML code inside a node, or an iframe? Is there a way to place in an image without needing to show inputs?

**Comment by chrisgoringe** [comment]
This might get you started:

https://github.com/chrisgoringe/Comfy-Custom-Node-How-To/wiki/custom_widget

**Comment by aegis72** [comment]
Thank you! That's a great place to start.

**Comment by geroldmeisinger** [comment]
I also like to say: thank you! :)
