### ISSUE TITLE
How to avoid duplicate loading

### ISSUE THREAD

**Issue by wolf95985** [chrisgoringe/Comfy-Custom-Node-How-To#8]
Hi,
I'm making some custom integration nodes that will have Checkpoint, CN, IPAdapter and other things, and now my trouble is that just by changing one of the other parameters, all the models will be reloaded, and I don't know if there is a way to prevent this unnecessary behavior, or any custom node that implements something similar?

**Comment by chrisgoringe** [comment]
In general if any input gets changed, the node will be re-executed. Without looking into code in detail it's hard to say much more - but my approach would probably be for the node to cache things it's loaded itself.
